services:
  - type: web
    name: zapateria-fercho-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/clientes
    autoDeploy: true 